report zrla_pedidos.

include zrla_event_alv.                 "classe de eventos em alv

include zrla_data_center.               "dados usados na app

include zrla_pedidos_status_0100o01.    "pbo tela 100
include zrla_pedidos_user_command_0i01. "pai tela 100

include zrla_pedidos_status_0200o01.    "pbo tela 200
include zrla_pedidos_user_command_0i02. "pai tela 200

include zrla_pedidos_status_0300o01.    "pbo tela 300
include zrla_pedidos_user_command_0i03. "pbo tela 300
